<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2024/04/16 00:02:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=td9ogk1hywxpd4ff;host=q2gen47hi68k1yrb.chr7pe7iynqr.eu-west-1.rds.amazonaws.com',
  'profiler' => false,
  'username' => 'y29ncspsgcn3yjym',
  'password' => 'm1tikrlekk7r680p',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
