<?php
// auto-generated by sfSecurityConfigHandler
// date: 2024/06/13 09:58:58
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
