name: Dispatch Cypress Tests
#test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to Cypress repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
            https://api.github.com/repos/AOURAGHLoubnaCGI/CGI-Demo-Tests/dispatches \
            -d '{"event_type":"run-cypress-tests"}'